### ISSUE TITLE
Make a distinction between language driver and language variant. 

### ISSUE THREAD

**Issue by okram** [qasaur/gremgo#1]
http://tinkerpop.apache.org/docs/3.2.1-SNAPSHOT/tutorials/gremlin-language-variants/

* **driver**: the machinery to connect to Gremlin Server (Websockets, etc.)
* **variant**: the machinery to write Gremlin in native Go.

**Comment by qasaur** [comment]
Thank you, for pointing this out, gremgo is a driver and not a language variant. I will make this clear in the readme.
