### ISSUE TITLE
Custom loader issue with DSE Graph

### ISSUE THREAD

**Issue by mandolyte** [qasaur/gremgo#12]
I have written a loader using this package and it works with Gremlin Server, but I cannot get it work against DSE Graph. The group thread below has some additional information. One of the responses to my question leads me to believe that gremgo must set a graph alias. Using the console, the setting looks like this:
`:remote config alias g followTopic.g`

The command given to gremgo is `graph.addVertex(label, "part", "name", PART)` with suitable bindings.

Whereas in the console you can set this once, I think I may have to send with each "transaction" with gremgo.

Of course, this may not even be the reason it is hanging, but I'll need the "g" alias once I start adding edges.

Here is the thread:
https://groups.google.com/forum/#!topic/gremlin-users/sjlzWPBJZ0k

Thanks in advance!
Cecil

**Comment by mandolyte** [comment]
I found more info on aliases [here](http://tinkerpop.apache.org/docs/current/reference/#_aliases). I think the map name in the struct/json should be "rebindings", but I can't find what the key/value pair should look like.

**Comment by qasaur** [comment]
Closing this issue because it has been fIxed in commit #13.
