### ISSUE TITLE
Breaking change in Gremlin Server 3.2.2

### ISSUE THREAD

**Issue by mandolyte** [qasaur/gremgo#14]
Info is here:
https://groups.google.com/forum/#!topic/gremlin-users/x4hiHsmTsHM

Since your dialer takes an IP address and port instead of URL, this might impact the method. I will not have 3.2.2 any time soon to test this myself.

Just wanted awareness.

Thanks,
Cecil

**Comment by qasaur** [comment]
Hi @mandolyte,

Thank you for letting me know. I'll make sure that the next gremgo update accommodates this change.

Thanks,
Marcus

**Comment by qasaur** [comment]
Fixed in #24.
