### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by clanstyles** [qasaur/gremgo#15]
How can I authenticate to a gremlin server?

**Comment by qasaur** [comment]
Hi clanstyles,

Authentication has not been implemented yet, but it is in the pipeline and will be implemented in the near future.

**Comment by qcade** [comment]
@qasaur do you need a hand with this? I wouldn't mind putting in a few hours if it helps.

**Comment by qasaur** [comment]
@qcade Sure, I'd appreciate it since it would certainly help with the backlog and I have no issues with that, just submit a pull request when you are done.

**Comment by ashwini-ms** [comment]
@qcade @qasaur , Anyone working on this?

**Comment by tejasmanohar** [comment]
@ashwini-ms probably not

**Comment by qasaur** [comment]
Fixed in #35
