### ISSUE TITLE
How to use gremgo to create a database

### ISSUE THREAD

**Issue by achandak123** [qasaur/gremgo#20]
Hi,
        I am just getting to understand gremlin. I am using neo4j plugin within gremlin server and trying to use gremgo. However, what i didn't understand is how to create a graph using gremgo? For eg, on gremlin console, we can do 

gr = Neo4j.open("trial")

Whats the equivalent of this in gremgo? or is gremgo only for query.

**Comment by achandak123** [comment]
Not an issue, the way this works is in the gremlin server, you can run a groovy script (configured in the gremlin server config file), which exposes the global variable g, which is the graph traversal. Once you have 'g', you can run your groovy scripts on it.

**Comment by ductrinhhuu** [comment]
Hi,
Would you please explain me a bit when you mention "which exposes the global variable g" and how to do it?
