### ISSUE TITLE
broken code in request.go

### ISSUE THREAD

**Issue by grantholly** [qasaur/gremgo#21]
I'm getting an error when I try to get this library.
```
$ go get github.com/qasaur/gremgo
# github.com/qasaur/gremgo
../../go/src/github.com/qasaur/gremgo/request.go:31:17: multiple-value uuid.NewV4() in single-value context
```
Looks like request.go is not using the uuid library correctly.  Here's the current code:
```
func prepareRequest(query string, bindings, rebindings map[string]string) (req request, id string) {
	id = uuid.NewV4().String()

	req.Requestid = id
	req.Op = "eval"
	req.Processor = ""

	req.Args = make(map[string]interface{})
	req.Args["language"] = "gremlin-groovy"
	req.Args["gremlin"] = query
	req.Args["bindings"] = bindings
	req.Args["rebindings"] = rebindings

	return
}
```
The problem is that uuid.NewV4() returns a (UUID, error) (https://godoc.org/github.com/satori/go.uuid#NewV4) but the calling code expects a single value and we are not doing anything the the error value.

**Comment by qasaur** [comment]
Closing this as it has been fixed in #22.
