### ISSUE TITLE
go get github.com/qasaur/gremgo returns an error

### ISSUE THREAD

**Issue by skuo-bl** [qasaur/gremgo#44]
Thank you for creating a go client.  When I received an error when running the 'go get' command.  Thank you for taking a look at it.

$ go get github.com/qasaur/gremgo
# github.com/qasaur/gremgo
../github.com/qasaur/gremgo/request.go:32:17: multiple-value uuid.NewV4() in single-value context

**Comment by skuo-bl** [comment]
I found link that discusses this issue: https://github.com/hlandau/acme/issues/293.  Apparently, doing a 'go build' generates the above error.

I have tried both go version 1.9.4 and 1.10.

**Comment by qasaur** [comment]
Thanks for letting me know @skuo-bl, I've fixed this issue now and `go get` should work without any major issues.

Let me know if any future problems arise. Closing this.

**Comment by brugnara** [comment]
Sadly:

```bash
go get -u github.com/qasaur/gremgo
# github.com/qasaur/gremgo/vendor/github.com/gorilla/websocket
../../go/src/github.com/qasaur/gremgo/vendor/github.com/gorilla/websocket/client.go:277:19: undefined: proxy_FromURL
../../go/src/github.com/qasaur/gremgo/vendor/github.com/gorilla/websocket/client.go:277:43: undefined: netDialerFunc
../../go/src/github.com/qasaur/gremgo/vendor/github.com/gorilla/websocket/client.go:317:10: undefined: doHandshakeWithTrace
../../go/src/github.com/qasaur/gremgo/vendor/github.com/gorilla/websocket/conn.go:393:10: c.writeBufs undefined (type *Conn has no field or methodwriteBufs)
```
