### ISSUE TITLE
Execute(query string, bindings map) function can take nil bindings?

### ISSUE THREAD

**Issue by kushal256** [qasaur/gremgo#6]
Can this function take nil for bindings?

I'm trying to run alot of addVertex() statements by calling Execute() funciton with bindings as nil.

When execute and try to print the response, I see just empty array "[]", but I see via my gremlin console the vertices were really added.  Am I allowed to pass in nil for this?  Please note there error was nil from Execute() call, also.

**Comment by qasaur** [comment]
Hi,

Do you get the same issue if you pass in an empy map instead of nil?

**Comment by kushal256** [comment]
Yes, I'm having issues getting any response.  See example:

for i := 0; i < 100; i++ {
		res, err := g.Execute(// Sends a query to Gremlin Server with bindings
			fmt.Sprintf("g.addV('label%v').property('testkey','testvalue')", i),
			map[string]string{},
		)
		if err != nil {
			fmt.Println(err)
			return
		}
		fmt.Println(res)  //Always prints [], even though can verify vertex got added via gremlin console with a label0, label1, label2, etc...
	}

	for i := 0; i < 2000; i++ {
		res, err := g.Execute(// Sends a query to Gremlin Server with bindings
			"g.V(x)",
			map[string]string{"x": fmt.Sprintf("%v", i)},
		)
		if err != nil {
			fmt.Println(err)
			return
		}
		fmt.Println(res)  //Always prints[], not sure if bindings are working
	}

	for i := 0; i < 2000; i++ {
		res, err := g.Execute(// Sends a query to Gremlin Server with bindings
			fmt.Sprintf("g.V(%v)", i),
			map[string]string{},
		)
		if err != nil {
			fmt.Println(err)
			return
		}
		fmt.Println(res)  //Always prints[], even though via gremlin console can verify g.V(0) exists
	}


Additionally, I periodically got an error, so I added this line to gremgo/client.go:

func (c *Client) executeRequest(query string, bindings map[string]string) (resp interface{}, err error) {
	req, id := prepareRequest(query, bindings)
	msg, err := packageRequest(req)
	if err != nil {
		fmt.Println(err)  // <-------------------------Added here
		return // TODO: Fix error handling
	}
	c.dispatchRequest(msg)
	resp = c.retrieveResponse(id)
	return
}


and when running that above code, randomly see this exception occur at different times.

goroutine 1 [running]:
runtime.throw(0x4b8280, 0x21)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:530 +0x90 fp=0xc82004bad8 sp=0xc82004bac0
runtime.mapaccess1_faststr(0x32cb60, 0xc820073170, 0xc8203fe210, 0x24, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/hashmap_fast.go:202 +0x5b fp=0xc82004bb38 sp=0xc82004bad8
github.com/qasaur/gremgo.(*Client).executeRequest(0xc820073110, 0x451948, 0x6, 0xc8203fe1e0, 0x0, 0x0, 0x0, 0x0)
	/Users/kushalkhan/dev/gowork/src/github.com/qasaur/gremgo/client.go:59 +0x2ef fp=0xc82004bcb8 sp=0xc82004bb38
github.com/qasaur/gremgo.(*Client).Execute(0xc820073110, 0x451948, 0x6, 0xc8203fe1e0, 0x0, 0x0, 0x0, 0x0)
	/Users/kushalkhan/dev/gowork/src/github.com/qasaur/gremgo/client.go:65 +0x5e fp=0xc82004bd00 sp=0xc82004bcb8
main.initGremlin()

**Comment by qasaur** [comment]
Thank you for bringing this up. I investigated the code further and discovered some issues and a critical race condition with the read worker and the read handler which caused the errors. It should be working properly now, but I'll wait until it has been resolved on your end before closing this issue.

Thanks,
Marcus

**Comment by kushal256** [comment]
Looks good now, thanks!!!

**Comment by qasaur** [comment]
Good to hear. Closing this issue seeing as the bug was resolved.
