### ISSUE TITLE
100% cpu usage?

### ISSUE THREAD

**Issue by kushal256** [qasaur/gremgo#9]
Things have been working well with this package, but noticed something strange.  I think it's taking 100% CPU after setting up a client, even when idle.

    dialer := gremgo.NewDialer("localhost:8182") 

	g, err := gremgo.Dial(dialer) // Returns a gremgo client to interact with

	if err != nil {

		fmt.Println(err)

		return

	}

       //Do something to idly wait

It appears to take 100% cpu.  Are you seeing the same thing?

**Comment by qasaur** [comment]
Hi kushal256,

Apologies for the rather late reply, I have been very busy lately so I haven't had much time to work on my open-source projects, but I did take a look at this bug and fixed it in the latest commit. Seemed to be a problem with the write worker being stuck in a loop and taking up a lot of CPU operations in the process. It should be fixed now.

Regards,

Marcus
